/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SalesTransactionAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("xtext/sales/assignment3/transaction/parser/antlr/internal/InternalSalesTransaction.tokens");
	}
}
