/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.assignment3.salestransaction.ui.internal.SalestransactionActivator;

public class SalesTransactionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SalestransactionActivator.getInstance().getInjector("xtext.sales.assignment3.transaction.SalesTransaction");
	}

}
