/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SalesTransactionGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CompanyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Company");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompanyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCodiceKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCodiceAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCodiceEStringParserRuleCall_3_1_0 = (RuleCall)cCodiceAssignment_3_1.eContents().get(0);
		private final Assignment cAddressAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAddressAddressParserRuleCall_4_0 = (RuleCall)cAddressAssignment_4.eContents().get(0);
		private final Keyword cStoresKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStoreAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStoreStoreParserRuleCall_7_0 = (RuleCall)cStoreAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStoreAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStoreStoreParserRuleCall_8_1_0 = (RuleCall)cStoreAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cTransactionsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cTransactionAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cTransactionTransactionParserRuleCall_10_2_0 = (RuleCall)cTransactionAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cTransactionAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cTransactionTransactionParserRuleCall_10_3_1_0 = (RuleCall)cTransactionAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Company returns Company:
		//    'company'
		//    name=EString
		//    '{'
		//        ('codice' codice=EString)?
		//        (address=Address)?
		//        'stores' '{' store+=Store ( "," store+=Store)* '}'
		//        ('transactions' '{' transaction+=Transaction ( "," transaction+=Transaction)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'company'
		//name=EString
		//'{'
		//    ('codice' codice=EString)?
		//    (address=Address)?
		//    'stores' '{' store+=Store ( "," store+=Store)* '}'
		//    ('transactions' '{' transaction+=Transaction ( "," transaction+=Transaction)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'company'
		public Keyword getCompanyKeyword_0() { return cCompanyKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('codice' codice=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'codice'
		public Keyword getCodiceKeyword_3_0() { return cCodiceKeyword_3_0; }
		
		//codice=EString
		public Assignment getCodiceAssignment_3_1() { return cCodiceAssignment_3_1; }
		
		//EString
		public RuleCall getCodiceEStringParserRuleCall_3_1_0() { return cCodiceEStringParserRuleCall_3_1_0; }
		
		//(address=Address)?
		public Assignment getAddressAssignment_4() { return cAddressAssignment_4; }
		
		//Address
		public RuleCall getAddressAddressParserRuleCall_4_0() { return cAddressAddressParserRuleCall_4_0; }
		
		//'stores'
		public Keyword getStoresKeyword_5() { return cStoresKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//store+=Store
		public Assignment getStoreAssignment_7() { return cStoreAssignment_7; }
		
		//Store
		public RuleCall getStoreStoreParserRuleCall_7_0() { return cStoreStoreParserRuleCall_7_0; }
		
		//( "," store+=Store)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//store+=Store
		public Assignment getStoreAssignment_8_1() { return cStoreAssignment_8_1; }
		
		//Store
		public RuleCall getStoreStoreParserRuleCall_8_1_0() { return cStoreStoreParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//('transactions' '{' transaction+=Transaction ( "," transaction+=Transaction)* '}' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'transactions'
		public Keyword getTransactionsKeyword_10_0() { return cTransactionsKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//transaction+=Transaction
		public Assignment getTransactionAssignment_10_2() { return cTransactionAssignment_10_2; }
		
		//Transaction
		public RuleCall getTransactionTransactionParserRuleCall_10_2_0() { return cTransactionTransactionParserRuleCall_10_2_0; }
		
		//( "," transaction+=Transaction)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//transaction+=Transaction
		public Assignment getTransactionAssignment_10_3_1() { return cTransactionAssignment_10_3_1; }
		
		//Transaction
		public RuleCall getTransactionTransactionParserRuleCall_10_3_1_0() { return cTransactionTransactionParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class AddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Address");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAddressAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAddressKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStreetKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStreetAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStreetEStringParserRuleCall_3_1_0 = (RuleCall)cStreetAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCityEStringParserRuleCall_4_1_0 = (RuleCall)cCityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCountryKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCountryAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCountryEStringParserRuleCall_5_1_0 = (RuleCall)cCountryAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTelephoneKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTelephoneAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTelephoneEStringParserRuleCall_6_1_0 = (RuleCall)cTelephoneAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Address returns Address:
		//    {Address}
		//    'address'
		//    '{'
		//        ('street' street=EString)?
		//        ('city' city=EString)?
		//        ('country' country=EString)?
		//        ('telephone' telephone=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Address}
		//'address'
		//'{'
		//    ('street' street=EString)?
		//    ('city' city=EString)?
		//    ('country' country=EString)?
		//    ('telephone' telephone=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Address}
		public Action getAddressAction_0() { return cAddressAction_0; }
		
		//'address'
		public Keyword getAddressKeyword_1() { return cAddressKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('street' street=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'street'
		public Keyword getStreetKeyword_3_0() { return cStreetKeyword_3_0; }
		
		//street=EString
		public Assignment getStreetAssignment_3_1() { return cStreetAssignment_3_1; }
		
		//EString
		public RuleCall getStreetEStringParserRuleCall_3_1_0() { return cStreetEStringParserRuleCall_3_1_0; }
		
		//('city' city=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'city'
		public Keyword getCityKeyword_4_0() { return cCityKeyword_4_0; }
		
		//city=EString
		public Assignment getCityAssignment_4_1() { return cCityAssignment_4_1; }
		
		//EString
		public RuleCall getCityEStringParserRuleCall_4_1_0() { return cCityEStringParserRuleCall_4_1_0; }
		
		//('country' country=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'country'
		public Keyword getCountryKeyword_5_0() { return cCountryKeyword_5_0; }
		
		//country=EString
		public Assignment getCountryAssignment_5_1() { return cCountryAssignment_5_1; }
		
		//EString
		public RuleCall getCountryEStringParserRuleCall_5_1_0() { return cCountryEStringParserRuleCall_5_1_0; }
		
		//('telephone' telephone=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'telephone'
		public Keyword getTelephoneKeyword_6_0() { return cTelephoneKeyword_6_0; }
		
		//telephone=EString
		public Assignment getTelephoneAssignment_6_1() { return cTelephoneAssignment_6_1; }
		
		//EString
		public RuleCall getTelephoneEStringParserRuleCall_6_1_0() { return cTelephoneEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class StoreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Store");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStoreAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStoreKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cItemsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cItemAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cItemItemParserRuleCall_4_2_0 = (RuleCall)cItemAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cItemAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cItemItemParserRuleCall_4_3_1_0 = (RuleCall)cItemAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Store returns Store:
		//    {Store}
		//    'store'
		//    name=EString
		//    '{'
		//        ('items' '{' item+=Item ( "," item+=Item)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Store}
		//'store'
		//name=EString
		//'{'
		//    ('items' '{' item+=Item ( "," item+=Item)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Store}
		public Action getStoreAction_0() { return cStoreAction_0; }
		
		//'store'
		public Keyword getStoreKeyword_1() { return cStoreKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('items' '{' item+=Item ( "," item+=Item)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'items'
		public Keyword getItemsKeyword_4_0() { return cItemsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//item+=Item
		public Assignment getItemAssignment_4_2() { return cItemAssignment_4_2; }
		
		//Item
		public RuleCall getItemItemParserRuleCall_4_2_0() { return cItemItemParserRuleCall_4_2_0; }
		
		//( "," item+=Item)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//item+=Item
		public Assignment getItemAssignment_4_3_1() { return cItemAssignment_4_3_1; }
		
		//Item
		public RuleCall getItemItemParserRuleCall_4_3_1_0() { return cItemItemParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TransactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Transaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransactionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTransactionNumberKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTransactionNumberAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTransactionNumberEStringParserRuleCall_2_1_0 = (RuleCall)cTransactionNumberAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIssuedDateKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIssuedDateAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIssuedDateEDateParserRuleCall_3_1_0 = (RuleCall)cIssuedDateAssignment_3_1.eContents().get(0);
		private final Keyword cTransactionTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTransactionTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTransactionTypeTransactionTypeEnumRuleCall_5_0 = (RuleCall)cTransactionTypeAssignment_5.eContents().get(0);
		private final Keyword cPaymentMethodKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPaymentMethodAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPaymentMethodPaymentMethodEnumRuleCall_7_0 = (RuleCall)cPaymentMethodAssignment_7.eContents().get(0);
		private final Assignment cCustomerAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCustomerCustomerParserRuleCall_8_0 = (RuleCall)cCustomerAssignment_8.eContents().get(0);
		private final Assignment cCashierAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCashierCashierParserRuleCall_9_0 = (RuleCall)cCashierAssignment_9.eContents().get(0);
		private final Keyword cLineItemsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cLineItemAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cLineItemLineItemParserRuleCall_12_0 = (RuleCall)cLineItemAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cLineItemAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cLineItemLineItemParserRuleCall_13_1_0 = (RuleCall)cLineItemAssignment_13_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cCardAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cCardCardParserRuleCall_15_0 = (RuleCall)cCardAssignment_15.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Transaction returns Transaction:
		//    'transaction'
		//    '{'
		//        ('transactionNumber' transactionNumber=EString)?
		//        ('issuedDate' issuedDate=EDate)?
		//        'transactionType' transactionType=TransactionType
		//        'paymentMethod' paymentMethod=PaymentMethod
		//        (customer=Customer)?
		//        (cashier=Cashier)?
		//        'lineItems' '{' lineItem+=LineItem ( "," lineItem+=LineItem)* '}'
		//        (card=Card)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'transaction'
		//'{'
		//    ('transactionNumber' transactionNumber=EString)?
		//    ('issuedDate' issuedDate=EDate)?
		//    'transactionType' transactionType=TransactionType
		//    'paymentMethod' paymentMethod=PaymentMethod
		//    (customer=Customer)?
		//    (cashier=Cashier)?
		//    'lineItems' '{' lineItem+=LineItem ( "," lineItem+=LineItem)* '}'
		//    (card=Card)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'transaction'
		public Keyword getTransactionKeyword_0() { return cTransactionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('transactionNumber' transactionNumber=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'transactionNumber'
		public Keyword getTransactionNumberKeyword_2_0() { return cTransactionNumberKeyword_2_0; }
		
		//transactionNumber=EString
		public Assignment getTransactionNumberAssignment_2_1() { return cTransactionNumberAssignment_2_1; }
		
		//EString
		public RuleCall getTransactionNumberEStringParserRuleCall_2_1_0() { return cTransactionNumberEStringParserRuleCall_2_1_0; }
		
		//('issuedDate' issuedDate=EDate)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'issuedDate'
		public Keyword getIssuedDateKeyword_3_0() { return cIssuedDateKeyword_3_0; }
		
		//issuedDate=EDate
		public Assignment getIssuedDateAssignment_3_1() { return cIssuedDateAssignment_3_1; }
		
		//EDate
		public RuleCall getIssuedDateEDateParserRuleCall_3_1_0() { return cIssuedDateEDateParserRuleCall_3_1_0; }
		
		//'transactionType'
		public Keyword getTransactionTypeKeyword_4() { return cTransactionTypeKeyword_4; }
		
		//transactionType=TransactionType
		public Assignment getTransactionTypeAssignment_5() { return cTransactionTypeAssignment_5; }
		
		//TransactionType
		public RuleCall getTransactionTypeTransactionTypeEnumRuleCall_5_0() { return cTransactionTypeTransactionTypeEnumRuleCall_5_0; }
		
		//'paymentMethod'
		public Keyword getPaymentMethodKeyword_6() { return cPaymentMethodKeyword_6; }
		
		//paymentMethod=PaymentMethod
		public Assignment getPaymentMethodAssignment_7() { return cPaymentMethodAssignment_7; }
		
		//PaymentMethod
		public RuleCall getPaymentMethodPaymentMethodEnumRuleCall_7_0() { return cPaymentMethodPaymentMethodEnumRuleCall_7_0; }
		
		//(customer=Customer)?
		public Assignment getCustomerAssignment_8() { return cCustomerAssignment_8; }
		
		//Customer
		public RuleCall getCustomerCustomerParserRuleCall_8_0() { return cCustomerCustomerParserRuleCall_8_0; }
		
		//(cashier=Cashier)?
		public Assignment getCashierAssignment_9() { return cCashierAssignment_9; }
		
		//Cashier
		public RuleCall getCashierCashierParserRuleCall_9_0() { return cCashierCashierParserRuleCall_9_0; }
		
		//'lineItems'
		public Keyword getLineItemsKeyword_10() { return cLineItemsKeyword_10; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//lineItem+=LineItem
		public Assignment getLineItemAssignment_12() { return cLineItemAssignment_12; }
		
		//LineItem
		public RuleCall getLineItemLineItemParserRuleCall_12_0() { return cLineItemLineItemParserRuleCall_12_0; }
		
		//( "," lineItem+=LineItem)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//lineItem+=LineItem
		public Assignment getLineItemAssignment_13_1() { return cLineItemAssignment_13_1; }
		
		//LineItem
		public RuleCall getLineItemLineItemParserRuleCall_13_1_0() { return cLineItemLineItemParserRuleCall_13_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//(card=Card)?
		public Assignment getCardAssignment_15() { return cCardAssignment_15; }
		
		//Card
		public RuleCall getCardCardParserRuleCall_15_0() { return cCardCardParserRuleCall_15_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	public class ItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Item");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cItemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCodeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCodeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_3_1_0 = (RuleCall)cCodeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBatchKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBatchAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBatchEStringParserRuleCall_4_1_0 = (RuleCall)cBatchAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Keyword cUomKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cUomAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cUomUoMEnumRuleCall_7_0 = (RuleCall)cUomAssignment_7.eContents().get(0);
		private final Keyword cAvailableNumberKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cAvailableNumberAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cAvailableNumberEDoubleParserRuleCall_9_0 = (RuleCall)cAvailableNumberAssignment_9.eContents().get(0);
		private final Keyword cIsActiveKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cIsActiveAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cIsActiveEBooleanParserRuleCall_11_0 = (RuleCall)cIsActiveAssignment_11.eContents().get(0);
		private final Keyword cUnitPriceKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cUnitPriceAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cUnitPricePriceParserRuleCall_13_0 = (RuleCall)cUnitPriceAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Item returns Item:
		//    'item'
		//    name=EString
		//    '{'
		//        ('code' code=EString)?
		//        ('batch' batch=EString)?
		//        ('description' description=EString)?
		//        'uom' uom=UoM
		//        'availableNumber' availableNumber=EDouble
		//        'isActive' isActive=EBoolean
		//        'unitPrice' unitPrice=Price
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'item'
		//name=EString
		//'{'
		//    ('code' code=EString)?
		//    ('batch' batch=EString)?
		//    ('description' description=EString)?
		//    'uom' uom=UoM
		//    'availableNumber' availableNumber=EDouble
		//    'isActive' isActive=EBoolean
		//    'unitPrice' unitPrice=Price
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'item'
		public Keyword getItemKeyword_0() { return cItemKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('code' code=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'code'
		public Keyword getCodeKeyword_3_0() { return cCodeKeyword_3_0; }
		
		//code=EString
		public Assignment getCodeAssignment_3_1() { return cCodeAssignment_3_1; }
		
		//EString
		public RuleCall getCodeEStringParserRuleCall_3_1_0() { return cCodeEStringParserRuleCall_3_1_0; }
		
		//('batch' batch=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'batch'
		public Keyword getBatchKeyword_4_0() { return cBatchKeyword_4_0; }
		
		//batch=EString
		public Assignment getBatchAssignment_4_1() { return cBatchAssignment_4_1; }
		
		//EString
		public RuleCall getBatchEStringParserRuleCall_4_1_0() { return cBatchEStringParserRuleCall_4_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//'uom'
		public Keyword getUomKeyword_6() { return cUomKeyword_6; }
		
		//uom=UoM
		public Assignment getUomAssignment_7() { return cUomAssignment_7; }
		
		//UoM
		public RuleCall getUomUoMEnumRuleCall_7_0() { return cUomUoMEnumRuleCall_7_0; }
		
		//'availableNumber'
		public Keyword getAvailableNumberKeyword_8() { return cAvailableNumberKeyword_8; }
		
		//availableNumber=EDouble
		public Assignment getAvailableNumberAssignment_9() { return cAvailableNumberAssignment_9; }
		
		//EDouble
		public RuleCall getAvailableNumberEDoubleParserRuleCall_9_0() { return cAvailableNumberEDoubleParserRuleCall_9_0; }
		
		//'isActive'
		public Keyword getIsActiveKeyword_10() { return cIsActiveKeyword_10; }
		
		//isActive=EBoolean
		public Assignment getIsActiveAssignment_11() { return cIsActiveAssignment_11; }
		
		//EBoolean
		public RuleCall getIsActiveEBooleanParserRuleCall_11_0() { return cIsActiveEBooleanParserRuleCall_11_0; }
		
		//'unitPrice'
		public Keyword getUnitPriceKeyword_12() { return cUnitPriceKeyword_12; }
		
		//unitPrice=Price
		public Assignment getUnitPriceAssignment_13() { return cUnitPriceAssignment_13; }
		
		//Price
		public RuleCall getUnitPricePriceParserRuleCall_13_0() { return cUnitPricePriceParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class PriceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Price");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPriceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSellingPriceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSellingPriceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSellingPriceEDoubleParserRuleCall_3_0 = (RuleCall)cSellingPriceAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Price returns Price:
		//    'price'
		//    '{'
		//        'sellingPrice' sellingPrice=EDouble
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'price'
		//'{'
		//    'sellingPrice' sellingPrice=EDouble
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'price'
		public Keyword getPriceKeyword_0() { return cPriceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'sellingPrice'
		public Keyword getSellingPriceKeyword_2() { return cSellingPriceKeyword_2; }
		
		//sellingPrice=EDouble
		public Assignment getSellingPriceAssignment_3() { return cSellingPriceAssignment_3; }
		
		//EDouble
		public RuleCall getSellingPriceEDoubleParserRuleCall_3_0() { return cSellingPriceEDoubleParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate returns ecore::EDate:
		//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCustomerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCustomerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSurNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSurNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSurNameEStringParserRuleCall_4_1_0 = (RuleCall)cSurNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdentityNumberKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdentityNumberAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdentityNumberEStringParserRuleCall_5_1_0 = (RuleCall)cIdentityNumberAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPhoneNumberKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPhoneNumberAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPhoneNumberEStringParserRuleCall_6_1_0 = (RuleCall)cPhoneNumberAssignment_6_1.eContents().get(0);
		private final Assignment cCardAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cCardCardCrossReference_7_0 = (CrossReference)cCardAssignment_7.eContents().get(0);
		private final RuleCall cCardCardEStringParserRuleCall_7_0_1 = (RuleCall)cCardCardCrossReference_7_0.eContents().get(1);
		private final Assignment cCustomerAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCustomerCustomerParserRuleCall_8_0 = (RuleCall)cCustomerAssignment_8.eContents().get(0);
		private final Assignment cCashierAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCashierCashierParserRuleCall_9_0 = (RuleCall)cCashierAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Customer returns Customer:
		//    {Customer}
		//    'customer'
		//    name=EString
		//    '{'
		//        ('surName' surName=EString)?
		//        ('identityNumber' identityNumber=EString)?
		//        ('phoneNumber' phoneNumber=EString)?
		//        (card=[Card|EString])?
		//        (customer=Customer)?
		//        (cashier=Cashier)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Customer}
		//'customer'
		//name=EString
		//'{'
		//    ('surName' surName=EString)?
		//    ('identityNumber' identityNumber=EString)?
		//    ('phoneNumber' phoneNumber=EString)?
		//    (card=[Card|EString])?
		//    (customer=Customer)?
		//    (cashier=Cashier)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Customer}
		public Action getCustomerAction_0() { return cCustomerAction_0; }
		
		//'customer'
		public Keyword getCustomerKeyword_1() { return cCustomerKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('surName' surName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'surName'
		public Keyword getSurNameKeyword_4_0() { return cSurNameKeyword_4_0; }
		
		//surName=EString
		public Assignment getSurNameAssignment_4_1() { return cSurNameAssignment_4_1; }
		
		//EString
		public RuleCall getSurNameEStringParserRuleCall_4_1_0() { return cSurNameEStringParserRuleCall_4_1_0; }
		
		//('identityNumber' identityNumber=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'identityNumber'
		public Keyword getIdentityNumberKeyword_5_0() { return cIdentityNumberKeyword_5_0; }
		
		//identityNumber=EString
		public Assignment getIdentityNumberAssignment_5_1() { return cIdentityNumberAssignment_5_1; }
		
		//EString
		public RuleCall getIdentityNumberEStringParserRuleCall_5_1_0() { return cIdentityNumberEStringParserRuleCall_5_1_0; }
		
		//('phoneNumber' phoneNumber=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'phoneNumber'
		public Keyword getPhoneNumberKeyword_6_0() { return cPhoneNumberKeyword_6_0; }
		
		//phoneNumber=EString
		public Assignment getPhoneNumberAssignment_6_1() { return cPhoneNumberAssignment_6_1; }
		
		//EString
		public RuleCall getPhoneNumberEStringParserRuleCall_6_1_0() { return cPhoneNumberEStringParserRuleCall_6_1_0; }
		
		//(card=[Card|EString])?
		public Assignment getCardAssignment_7() { return cCardAssignment_7; }
		
		//[Card|EString]
		public CrossReference getCardCardCrossReference_7_0() { return cCardCardCrossReference_7_0; }
		
		//EString
		public RuleCall getCardCardEStringParserRuleCall_7_0_1() { return cCardCardEStringParserRuleCall_7_0_1; }
		
		//(customer=Customer)?
		public Assignment getCustomerAssignment_8() { return cCustomerAssignment_8; }
		
		//Customer
		public RuleCall getCustomerCustomerParserRuleCall_8_0() { return cCustomerCustomerParserRuleCall_8_0; }
		
		//(cashier=Cashier)?
		public Assignment getCashierAssignment_9() { return cCashierAssignment_9; }
		
		//Cashier
		public RuleCall getCashierCashierParserRuleCall_9_0() { return cCashierCashierParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class CashierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Cashier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCashierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCashierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSurNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSurNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSurNameEStringParserRuleCall_4_1_0 = (RuleCall)cSurNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEmployeeIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cEmployeeIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cEmployeeIdEStringParserRuleCall_5_1_0 = (RuleCall)cEmployeeIdAssignment_5_1.eContents().get(0);
		private final Assignment cCustomerAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCustomerCustomerParserRuleCall_6_0 = (RuleCall)cCustomerAssignment_6.eContents().get(0);
		private final Assignment cCashierAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCashierCashierParserRuleCall_7_0 = (RuleCall)cCashierAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Cashier returns Cashier:
		//    {Cashier}
		//    'cashier'
		//    name=EString
		//    '{'
		//        ('surName' surName=EString)?
		//        ('employeeId' employeeId=EString)?
		//        (customer=Customer)?
		//        (cashier=Cashier)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Cashier}
		//'cashier'
		//name=EString
		//'{'
		//    ('surName' surName=EString)?
		//    ('employeeId' employeeId=EString)?
		//    (customer=Customer)?
		//    (cashier=Cashier)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Cashier}
		public Action getCashierAction_0() { return cCashierAction_0; }
		
		//'cashier'
		public Keyword getCashierKeyword_1() { return cCashierKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('surName' surName=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'surName'
		public Keyword getSurNameKeyword_4_0() { return cSurNameKeyword_4_0; }
		
		//surName=EString
		public Assignment getSurNameAssignment_4_1() { return cSurNameAssignment_4_1; }
		
		//EString
		public RuleCall getSurNameEStringParserRuleCall_4_1_0() { return cSurNameEStringParserRuleCall_4_1_0; }
		
		//('employeeId' employeeId=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'employeeId'
		public Keyword getEmployeeIdKeyword_5_0() { return cEmployeeIdKeyword_5_0; }
		
		//employeeId=EString
		public Assignment getEmployeeIdAssignment_5_1() { return cEmployeeIdAssignment_5_1; }
		
		//EString
		public RuleCall getEmployeeIdEStringParserRuleCall_5_1_0() { return cEmployeeIdEStringParserRuleCall_5_1_0; }
		
		//(customer=Customer)?
		public Assignment getCustomerAssignment_6() { return cCustomerAssignment_6; }
		
		//Customer
		public RuleCall getCustomerCustomerParserRuleCall_6_0() { return cCustomerCustomerParserRuleCall_6_0; }
		
		//(cashier=Cashier)?
		public Assignment getCashierAssignment_7() { return cCashierAssignment_7; }
		
		//Cashier
		public RuleCall getCashierCashierParserRuleCall_7_0() { return cCashierCashierParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class LineItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.LineItem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLineItemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCodeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCodeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCodeEStringParserRuleCall_2_1_0 = (RuleCall)cCodeAssignment_2_1.eContents().get(0);
		private final Keyword cQuantityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuantityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuantityEDoubleParserRuleCall_4_0 = (RuleCall)cQuantityAssignment_4.eContents().get(0);
		private final Keyword cItemKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cItemAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cItemItemCrossReference_6_0 = (CrossReference)cItemAssignment_6.eContents().get(0);
		private final RuleCall cItemItemEStringParserRuleCall_6_0_1 = (RuleCall)cItemItemCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTaxKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTaxAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTaxTaxParserRuleCall_7_1_0 = (RuleCall)cTaxAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDiscountKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDiscountAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDiscountDiscountParserRuleCall_8_1_0 = (RuleCall)cDiscountAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAdditionalChargeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cAdditionalChargeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cAdditionalChargeAdditionalChargeParserRuleCall_9_1_0 = (RuleCall)cAdditionalChargeAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//LineItem returns LineItem:
		//    'lineItem'
		//    '{'
		//        ('code' code=EString)?
		//        'quantity' quantity=EDouble
		//        'item' item=[Item|EString]
		//        ('tax' tax=Tax)?
		//        ('discount' discount=Discount)?
		//        ('additionalCharge' additionalCharge=AdditionalCharge)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'lineItem'
		//'{'
		//    ('code' code=EString)?
		//    'quantity' quantity=EDouble
		//    'item' item=[Item|EString]
		//    ('tax' tax=Tax)?
		//    ('discount' discount=Discount)?
		//    ('additionalCharge' additionalCharge=AdditionalCharge)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'lineItem'
		public Keyword getLineItemKeyword_0() { return cLineItemKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('code' code=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'code'
		public Keyword getCodeKeyword_2_0() { return cCodeKeyword_2_0; }
		
		//code=EString
		public Assignment getCodeAssignment_2_1() { return cCodeAssignment_2_1; }
		
		//EString
		public RuleCall getCodeEStringParserRuleCall_2_1_0() { return cCodeEStringParserRuleCall_2_1_0; }
		
		//'quantity'
		public Keyword getQuantityKeyword_3() { return cQuantityKeyword_3; }
		
		//quantity=EDouble
		public Assignment getQuantityAssignment_4() { return cQuantityAssignment_4; }
		
		//EDouble
		public RuleCall getQuantityEDoubleParserRuleCall_4_0() { return cQuantityEDoubleParserRuleCall_4_0; }
		
		//'item'
		public Keyword getItemKeyword_5() { return cItemKeyword_5; }
		
		//item=[Item|EString]
		public Assignment getItemAssignment_6() { return cItemAssignment_6; }
		
		//[Item|EString]
		public CrossReference getItemItemCrossReference_6_0() { return cItemItemCrossReference_6_0; }
		
		//EString
		public RuleCall getItemItemEStringParserRuleCall_6_0_1() { return cItemItemEStringParserRuleCall_6_0_1; }
		
		//('tax' tax=Tax)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'tax'
		public Keyword getTaxKeyword_7_0() { return cTaxKeyword_7_0; }
		
		//tax=Tax
		public Assignment getTaxAssignment_7_1() { return cTaxAssignment_7_1; }
		
		//Tax
		public RuleCall getTaxTaxParserRuleCall_7_1_0() { return cTaxTaxParserRuleCall_7_1_0; }
		
		//('discount' discount=Discount)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'discount'
		public Keyword getDiscountKeyword_8_0() { return cDiscountKeyword_8_0; }
		
		//discount=Discount
		public Assignment getDiscountAssignment_8_1() { return cDiscountAssignment_8_1; }
		
		//Discount
		public RuleCall getDiscountDiscountParserRuleCall_8_1_0() { return cDiscountDiscountParserRuleCall_8_1_0; }
		
		//('additionalCharge' additionalCharge=AdditionalCharge)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'additionalCharge'
		public Keyword getAdditionalChargeKeyword_9_0() { return cAdditionalChargeKeyword_9_0; }
		
		//additionalCharge=AdditionalCharge
		public Assignment getAdditionalChargeAssignment_9_1() { return cAdditionalChargeAssignment_9_1; }
		
		//AdditionalCharge
		public RuleCall getAdditionalChargeAdditionalChargeParserRuleCall_9_1_0() { return cAdditionalChargeAdditionalChargeParserRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class CardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Card");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCardNumberKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCardNumberAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCardNumberEStringParserRuleCall_2_1_0 = (RuleCall)cCardNumberAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cExpiryDateKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cExpiryDateAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cExpiryDateEStringParserRuleCall_3_1_0 = (RuleCall)cExpiryDateAssignment_3_1.eContents().get(0);
		private final Keyword cCardHolderKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCardHolderAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cCardHolderCustomerCrossReference_5_0 = (CrossReference)cCardHolderAssignment_5.eContents().get(0);
		private final RuleCall cCardHolderCustomerEStringParserRuleCall_5_0_1 = (RuleCall)cCardHolderCustomerCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Card returns Card:
		//    'card'
		//    '{'
		//        ('cardNumber' cardNumber=EString)?
		//        ('expiryDate' expiryDate=EString)?
		//        'cardHolder' cardHolder=[Customer|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'card'
		//'{'
		//    ('cardNumber' cardNumber=EString)?
		//    ('expiryDate' expiryDate=EString)?
		//    'cardHolder' cardHolder=[Customer|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'card'
		public Keyword getCardKeyword_0() { return cCardKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('cardNumber' cardNumber=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'cardNumber'
		public Keyword getCardNumberKeyword_2_0() { return cCardNumberKeyword_2_0; }
		
		//cardNumber=EString
		public Assignment getCardNumberAssignment_2_1() { return cCardNumberAssignment_2_1; }
		
		//EString
		public RuleCall getCardNumberEStringParserRuleCall_2_1_0() { return cCardNumberEStringParserRuleCall_2_1_0; }
		
		//('expiryDate' expiryDate=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'expiryDate'
		public Keyword getExpiryDateKeyword_3_0() { return cExpiryDateKeyword_3_0; }
		
		//expiryDate=EString
		public Assignment getExpiryDateAssignment_3_1() { return cExpiryDateAssignment_3_1; }
		
		//EString
		public RuleCall getExpiryDateEStringParserRuleCall_3_1_0() { return cExpiryDateEStringParserRuleCall_3_1_0; }
		
		//'cardHolder'
		public Keyword getCardHolderKeyword_4() { return cCardHolderKeyword_4; }
		
		//cardHolder=[Customer|EString]
		public Assignment getCardHolderAssignment_5() { return cCardHolderAssignment_5; }
		
		//[Customer|EString]
		public CrossReference getCardHolderCustomerCrossReference_5_0() { return cCardHolderCustomerCrossReference_5_0; }
		
		//EString
		public RuleCall getCardHolderCustomerEStringParserRuleCall_5_0_1() { return cCardHolderCustomerEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TaxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Tax");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTaxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTaxTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTaxTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTaxTypeTaxTypeEnumRuleCall_3_0 = (RuleCall)cTaxTypeAssignment_3.eContents().get(0);
		private final Keyword cTaxableAmountKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTaxableAmountAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTaxableAmountEDoubleParserRuleCall_5_0 = (RuleCall)cTaxableAmountAssignment_5.eContents().get(0);
		private final Keyword cTaxAmountKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTaxAmountAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTaxAmountEDoubleParserRuleCall_7_0 = (RuleCall)cTaxAmountAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Tax returns Tax:
		//    'tax'
		//    '{'
		//        'taxType' taxType=TaxType
		//        'taxableAmount' taxableAmount=EDouble
		//        'taxAmount' taxAmount=EDouble
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'tax'
		//'{'
		//    'taxType' taxType=TaxType
		//    'taxableAmount' taxableAmount=EDouble
		//    'taxAmount' taxAmount=EDouble
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'tax'
		public Keyword getTaxKeyword_0() { return cTaxKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'taxType'
		public Keyword getTaxTypeKeyword_2() { return cTaxTypeKeyword_2; }
		
		//taxType=TaxType
		public Assignment getTaxTypeAssignment_3() { return cTaxTypeAssignment_3; }
		
		//TaxType
		public RuleCall getTaxTypeTaxTypeEnumRuleCall_3_0() { return cTaxTypeTaxTypeEnumRuleCall_3_0; }
		
		//'taxableAmount'
		public Keyword getTaxableAmountKeyword_4() { return cTaxableAmountKeyword_4; }
		
		//taxableAmount=EDouble
		public Assignment getTaxableAmountAssignment_5() { return cTaxableAmountAssignment_5; }
		
		//EDouble
		public RuleCall getTaxableAmountEDoubleParserRuleCall_5_0() { return cTaxableAmountEDoubleParserRuleCall_5_0; }
		
		//'taxAmount'
		public Keyword getTaxAmountKeyword_6() { return cTaxAmountKeyword_6; }
		
		//taxAmount=EDouble
		public Assignment getTaxAmountAssignment_7() { return cTaxAmountAssignment_7; }
		
		//EDouble
		public RuleCall getTaxAmountEDoubleParserRuleCall_7_0() { return cTaxAmountEDoubleParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DiscountElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.Discount");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDiscountKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPercentageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPercentageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPercentageEDoubleParserRuleCall_3_0 = (RuleCall)cPercentageAssignment_3.eContents().get(0);
		private final Keyword cAmountKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAmountAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAmountEDoubleParserRuleCall_5_0 = (RuleCall)cAmountAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Discount returns Discount:
		//    'discount'
		//    '{'
		//        'percentage' percentage=EDouble
		//        'amount' amount=EDouble
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'discount'
		//'{'
		//    'percentage' percentage=EDouble
		//    'amount' amount=EDouble
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'discount'
		public Keyword getDiscountKeyword_0() { return cDiscountKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'percentage'
		public Keyword getPercentageKeyword_2() { return cPercentageKeyword_2; }
		
		//percentage=EDouble
		public Assignment getPercentageAssignment_3() { return cPercentageAssignment_3; }
		
		//EDouble
		public RuleCall getPercentageEDoubleParserRuleCall_3_0() { return cPercentageEDoubleParserRuleCall_3_0; }
		
		//'amount'
		public Keyword getAmountKeyword_4() { return cAmountKeyword_4; }
		
		//amount=EDouble
		public Assignment getAmountAssignment_5() { return cAmountAssignment_5; }
		
		//EDouble
		public RuleCall getAmountEDoubleParserRuleCall_5_0() { return cAmountEDoubleParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AdditionalChargeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.AdditionalCharge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAdditionalChargeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cServiceChargeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cServiceChargeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cServiceChargeEDoubleParserRuleCall_3_0 = (RuleCall)cServiceChargeAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AdditionalCharge returns AdditionalCharge:
		//    'additionalCharge'
		//    '{'
		//        'serviceCharge' serviceCharge=EDouble
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'additionalCharge'
		//'{'
		//    'serviceCharge' serviceCharge=EDouble
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'additionalCharge'
		public Keyword getAdditionalChargeKeyword_0() { return cAdditionalChargeKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'serviceCharge'
		public Keyword getServiceChargeKeyword_2() { return cServiceChargeKeyword_2; }
		
		//serviceCharge=EDouble
		public Assignment getServiceChargeAssignment_3() { return cServiceChargeAssignment_3; }
		
		//EDouble
		public RuleCall getServiceChargeEDoubleParserRuleCall_3_0() { return cServiceChargeEDoubleParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class UoMElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.UoM");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPCSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPCSPCSKeyword_0_0 = (Keyword)cPCSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cKGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cKGKGKeyword_1_0 = (Keyword)cKGEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLTREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLTRLTRKeyword_2_0 = (Keyword)cLTREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMMKeyword_3_0 = (Keyword)cMEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum UoM returns UoM:
		//                PCS = 'PCS' | KG = 'KG' | LTR = 'LTR' | M = 'M';
		public EnumRule getRule() { return rule; }
		
		//PCS = 'PCS' | KG = 'KG' | LTR = 'LTR' | M = 'M'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PCS = 'PCS'
		public EnumLiteralDeclaration getPCSEnumLiteralDeclaration_0() { return cPCSEnumLiteralDeclaration_0; }
		
		//'PCS'
		public Keyword getPCSPCSKeyword_0_0() { return cPCSPCSKeyword_0_0; }
		
		//KG = 'KG'
		public EnumLiteralDeclaration getKGEnumLiteralDeclaration_1() { return cKGEnumLiteralDeclaration_1; }
		
		//'KG'
		public Keyword getKGKGKeyword_1_0() { return cKGKGKeyword_1_0; }
		
		//LTR = 'LTR'
		public EnumLiteralDeclaration getLTREnumLiteralDeclaration_2() { return cLTREnumLiteralDeclaration_2; }
		
		//'LTR'
		public Keyword getLTRLTRKeyword_2_0() { return cLTRLTRKeyword_2_0; }
		
		//M = 'M'
		public EnumLiteralDeclaration getMEnumLiteralDeclaration_3() { return cMEnumLiteralDeclaration_3; }
		
		//'M'
		public Keyword getMMKeyword_3_0() { return cMMKeyword_3_0; }
	}
	public class TransactionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.TransactionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCashSalesEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCashSalesCashSalesKeyword_0_0 = (Keyword)cCashSalesEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCreditSalesEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCreditSalesCreditSalesKeyword_1_0 = (Keyword)cCreditSalesEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAdvancePaymentSalesEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAdvancePaymentSalesAdvancePaymentSalesKeyword_2_0 = (Keyword)cAdvancePaymentSalesEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TransactionType returns TransactionType:
		//                CashSales = 'CashSales' | CreditSales = 'CreditSales' | AdvancePaymentSales = 'AdvancePaymentSales';
		public EnumRule getRule() { return rule; }
		
		//CashSales = 'CashSales' | CreditSales = 'CreditSales' | AdvancePaymentSales = 'AdvancePaymentSales'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CashSales = 'CashSales'
		public EnumLiteralDeclaration getCashSalesEnumLiteralDeclaration_0() { return cCashSalesEnumLiteralDeclaration_0; }
		
		//'CashSales'
		public Keyword getCashSalesCashSalesKeyword_0_0() { return cCashSalesCashSalesKeyword_0_0; }
		
		//CreditSales = 'CreditSales'
		public EnumLiteralDeclaration getCreditSalesEnumLiteralDeclaration_1() { return cCreditSalesEnumLiteralDeclaration_1; }
		
		//'CreditSales'
		public Keyword getCreditSalesCreditSalesKeyword_1_0() { return cCreditSalesCreditSalesKeyword_1_0; }
		
		//AdvancePaymentSales = 'AdvancePaymentSales'
		public EnumLiteralDeclaration getAdvancePaymentSalesEnumLiteralDeclaration_2() { return cAdvancePaymentSalesEnumLiteralDeclaration_2; }
		
		//'AdvancePaymentSales'
		public Keyword getAdvancePaymentSalesAdvancePaymentSalesKeyword_2_0() { return cAdvancePaymentSalesAdvancePaymentSalesKeyword_2_0; }
	}
	public class PaymentMethodElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.PaymentMethod");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCashEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCashCashKeyword_0_0 = (Keyword)cCashEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCardEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCardCardKeyword_1_0 = (Keyword)cCardEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum PaymentMethod returns PaymentMethod:
		//                Cash = 'Cash' | Card = 'Card';
		public EnumRule getRule() { return rule; }
		
		//Cash = 'Cash' | Card = 'Card'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Cash = 'Cash'
		public EnumLiteralDeclaration getCashEnumLiteralDeclaration_0() { return cCashEnumLiteralDeclaration_0; }
		
		//'Cash'
		public Keyword getCashCashKeyword_0_0() { return cCashCashKeyword_0_0; }
		
		//Card = 'Card'
		public EnumLiteralDeclaration getCardEnumLiteralDeclaration_1() { return cCardEnumLiteralDeclaration_1; }
		
		//'Card'
		public Keyword getCardCardKeyword_1_0() { return cCardCardKeyword_1_0; }
	}
	public class TaxTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.sales.assignment3.transaction.SalesTransaction.TaxType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTaxExemptEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTaxExemptTaxExemptKeyword_0_0 = (Keyword)cTaxExemptEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIncomeTaxEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIncomeTaxIncomeTaxKeyword_1_0 = (Keyword)cIncomeTaxEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCorporateTaxEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCorporateTaxCorporateTaxKeyword_2_0 = (Keyword)cCorporateTaxEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cVATEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cVATVATKeyword_3_0 = (Keyword)cVATEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum TaxType returns TaxType:
		//                TaxExempt = 'TaxExempt' | IncomeTax = 'IncomeTax' | CorporateTax = 'CorporateTax' | VAT = 'VAT';
		public EnumRule getRule() { return rule; }
		
		//TaxExempt = 'TaxExempt' | IncomeTax = 'IncomeTax' | CorporateTax = 'CorporateTax' | VAT = 'VAT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TaxExempt = 'TaxExempt'
		public EnumLiteralDeclaration getTaxExemptEnumLiteralDeclaration_0() { return cTaxExemptEnumLiteralDeclaration_0; }
		
		//'TaxExempt'
		public Keyword getTaxExemptTaxExemptKeyword_0_0() { return cTaxExemptTaxExemptKeyword_0_0; }
		
		//IncomeTax = 'IncomeTax'
		public EnumLiteralDeclaration getIncomeTaxEnumLiteralDeclaration_1() { return cIncomeTaxEnumLiteralDeclaration_1; }
		
		//'IncomeTax'
		public Keyword getIncomeTaxIncomeTaxKeyword_1_0() { return cIncomeTaxIncomeTaxKeyword_1_0; }
		
		//CorporateTax = 'CorporateTax'
		public EnumLiteralDeclaration getCorporateTaxEnumLiteralDeclaration_2() { return cCorporateTaxEnumLiteralDeclaration_2; }
		
		//'CorporateTax'
		public Keyword getCorporateTaxCorporateTaxKeyword_2_0() { return cCorporateTaxCorporateTaxKeyword_2_0; }
		
		//VAT = 'VAT'
		public EnumLiteralDeclaration getVATEnumLiteralDeclaration_3() { return cVATEnumLiteralDeclaration_3; }
		
		//'VAT'
		public Keyword getVATVATKeyword_3_0() { return cVATVATKeyword_3_0; }
	}
	
	private final CompanyElements pCompany;
	private final EStringElements pEString;
	private final AddressElements pAddress;
	private final StoreElements pStore;
	private final TransactionElements pTransaction;
	private final ItemElements pItem;
	private final UoMElements eUoM;
	private final EDoubleElements pEDouble;
	private final PriceElements pPrice;
	private final EBooleanElements pEBoolean;
	private final EDateElements pEDate;
	private final TransactionTypeElements eTransactionType;
	private final PaymentMethodElements ePaymentMethod;
	private final CustomerElements pCustomer;
	private final CashierElements pCashier;
	private final LineItemElements pLineItem;
	private final CardElements pCard;
	private final TaxElements pTax;
	private final DiscountElements pDiscount;
	private final AdditionalChargeElements pAdditionalCharge;
	private final TaxTypeElements eTaxType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SalesTransactionGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCompany = new CompanyElements();
		this.pEString = new EStringElements();
		this.pAddress = new AddressElements();
		this.pStore = new StoreElements();
		this.pTransaction = new TransactionElements();
		this.pItem = new ItemElements();
		this.eUoM = new UoMElements();
		this.pEDouble = new EDoubleElements();
		this.pPrice = new PriceElements();
		this.pEBoolean = new EBooleanElements();
		this.pEDate = new EDateElements();
		this.eTransactionType = new TransactionTypeElements();
		this.ePaymentMethod = new PaymentMethodElements();
		this.pCustomer = new CustomerElements();
		this.pCashier = new CashierElements();
		this.pLineItem = new LineItemElements();
		this.pCard = new CardElements();
		this.pTax = new TaxElements();
		this.pDiscount = new DiscountElements();
		this.pAdditionalCharge = new AdditionalChargeElements();
		this.eTaxType = new TaxTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtext.sales.assignment3.transaction.SalesTransaction".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Company returns Company:
	//    'company'
	//    name=EString
	//    '{'
	//        ('codice' codice=EString)?
	//        (address=Address)?
	//        'stores' '{' store+=Store ( "," store+=Store)* '}'
	//        ('transactions' '{' transaction+=Transaction ( "," transaction+=Transaction)* '}' )?
	//    '}';
	public CompanyElements getCompanyAccess() {
		return pCompany;
	}
	
	public ParserRule getCompanyRule() {
		return getCompanyAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Address returns Address:
	//    {Address}
	//    'address'
	//    '{'
	//        ('street' street=EString)?
	//        ('city' city=EString)?
	//        ('country' country=EString)?
	//        ('telephone' telephone=EString)?
	//    '}';
	public AddressElements getAddressAccess() {
		return pAddress;
	}
	
	public ParserRule getAddressRule() {
		return getAddressAccess().getRule();
	}
	
	//Store returns Store:
	//    {Store}
	//    'store'
	//    name=EString
	//    '{'
	//        ('items' '{' item+=Item ( "," item+=Item)* '}' )?
	//    '}';
	public StoreElements getStoreAccess() {
		return pStore;
	}
	
	public ParserRule getStoreRule() {
		return getStoreAccess().getRule();
	}
	
	//Transaction returns Transaction:
	//    'transaction'
	//    '{'
	//        ('transactionNumber' transactionNumber=EString)?
	//        ('issuedDate' issuedDate=EDate)?
	//        'transactionType' transactionType=TransactionType
	//        'paymentMethod' paymentMethod=PaymentMethod
	//        (customer=Customer)?
	//        (cashier=Cashier)?
	//        'lineItems' '{' lineItem+=LineItem ( "," lineItem+=LineItem)* '}'
	//        (card=Card)?
	//    '}';
	public TransactionElements getTransactionAccess() {
		return pTransaction;
	}
	
	public ParserRule getTransactionRule() {
		return getTransactionAccess().getRule();
	}
	
	//Item returns Item:
	//    'item'
	//    name=EString
	//    '{'
	//        ('code' code=EString)?
	//        ('batch' batch=EString)?
	//        ('description' description=EString)?
	//        'uom' uom=UoM
	//        'availableNumber' availableNumber=EDouble
	//        'isActive' isActive=EBoolean
	//        'unitPrice' unitPrice=Price
	//    '}';
	public ItemElements getItemAccess() {
		return pItem;
	}
	
	public ParserRule getItemRule() {
		return getItemAccess().getRule();
	}
	
	//enum UoM returns UoM:
	//                PCS = 'PCS' | KG = 'KG' | LTR = 'LTR' | M = 'M';
	public UoMElements getUoMAccess() {
		return eUoM;
	}
	
	public EnumRule getUoMRule() {
		return getUoMAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//Price returns Price:
	//    'price'
	//    '{'
	//        'sellingPrice' sellingPrice=EDouble
	//    '}';
	public PriceElements getPriceAccess() {
		return pPrice;
	}
	
	public ParserRule getPriceRule() {
		return getPriceAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EDate returns ecore::EDate:
	//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//enum TransactionType returns TransactionType:
	//                CashSales = 'CashSales' | CreditSales = 'CreditSales' | AdvancePaymentSales = 'AdvancePaymentSales';
	public TransactionTypeElements getTransactionTypeAccess() {
		return eTransactionType;
	}
	
	public EnumRule getTransactionTypeRule() {
		return getTransactionTypeAccess().getRule();
	}
	
	//enum PaymentMethod returns PaymentMethod:
	//                Cash = 'Cash' | Card = 'Card';
	public PaymentMethodElements getPaymentMethodAccess() {
		return ePaymentMethod;
	}
	
	public EnumRule getPaymentMethodRule() {
		return getPaymentMethodAccess().getRule();
	}
	
	//Customer returns Customer:
	//    {Customer}
	//    'customer'
	//    name=EString
	//    '{'
	//        ('surName' surName=EString)?
	//        ('identityNumber' identityNumber=EString)?
	//        ('phoneNumber' phoneNumber=EString)?
	//        (card=[Card|EString])?
	//        (customer=Customer)?
	//        (cashier=Cashier)?
	//    '}';
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}
	
	//Cashier returns Cashier:
	//    {Cashier}
	//    'cashier'
	//    name=EString
	//    '{'
	//        ('surName' surName=EString)?
	//        ('employeeId' employeeId=EString)?
	//        (customer=Customer)?
	//        (cashier=Cashier)?
	//    '}';
	public CashierElements getCashierAccess() {
		return pCashier;
	}
	
	public ParserRule getCashierRule() {
		return getCashierAccess().getRule();
	}
	
	//LineItem returns LineItem:
	//    'lineItem'
	//    '{'
	//        ('code' code=EString)?
	//        'quantity' quantity=EDouble
	//        'item' item=[Item|EString]
	//        ('tax' tax=Tax)?
	//        ('discount' discount=Discount)?
	//        ('additionalCharge' additionalCharge=AdditionalCharge)?
	//    '}';
	public LineItemElements getLineItemAccess() {
		return pLineItem;
	}
	
	public ParserRule getLineItemRule() {
		return getLineItemAccess().getRule();
	}
	
	//Card returns Card:
	//    'card'
	//    '{'
	//        ('cardNumber' cardNumber=EString)?
	//        ('expiryDate' expiryDate=EString)?
	//        'cardHolder' cardHolder=[Customer|EString]
	//    '}';
	public CardElements getCardAccess() {
		return pCard;
	}
	
	public ParserRule getCardRule() {
		return getCardAccess().getRule();
	}
	
	//Tax returns Tax:
	//    'tax'
	//    '{'
	//        'taxType' taxType=TaxType
	//        'taxableAmount' taxableAmount=EDouble
	//        'taxAmount' taxAmount=EDouble
	//    '}';
	public TaxElements getTaxAccess() {
		return pTax;
	}
	
	public ParserRule getTaxRule() {
		return getTaxAccess().getRule();
	}
	
	//Discount returns Discount:
	//    'discount'
	//    '{'
	//        'percentage' percentage=EDouble
	//        'amount' amount=EDouble
	//    '}';
	public DiscountElements getDiscountAccess() {
		return pDiscount;
	}
	
	public ParserRule getDiscountRule() {
		return getDiscountAccess().getRule();
	}
	
	//AdditionalCharge returns AdditionalCharge:
	//    'additionalCharge'
	//    '{'
	//        'serviceCharge' serviceCharge=EDouble
	//    '}';
	public AdditionalChargeElements getAdditionalChargeAccess() {
		return pAdditionalCharge;
	}
	
	public ParserRule getAdditionalChargeRule() {
		return getAdditionalChargeAccess().getRule();
	}
	
	//enum TaxType returns TaxType:
	//                TaxExempt = 'TaxExempt' | IncomeTax = 'IncomeTax' | CorporateTax = 'CorporateTax' | VAT = 'VAT';
	public TaxTypeElements getTaxTypeAccess() {
		return eTaxType;
	}
	
	public EnumRule getTaxTypeRule() {
		return getTaxTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
