/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.sales.assignment3.transaction.SalesTransactionRuntimeModule;
import xtext.sales.assignment3.transaction.SalesTransactionStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SalesTransactionIdeSetup extends SalesTransactionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SalesTransactionRuntimeModule(), new SalesTransactionIdeModule()));
	}
	
}
