/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ide;


/**
 * Use this class to register ide components.
 */
public class SalesTransactionIdeModule extends AbstractSalesTransactionIdeModule {
}
