/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSalesTransactionScopeProvider extends DelegatingScopeProvider {
}
