/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xtext.sales.assignment3.transaction.ide.contentassist.antlr.internal.InternalSalesTransactionParser;
import xtext.sales.assignment3.transaction.services.SalesTransactionGrammarAccess;

public class SalesTransactionParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SalesTransactionGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SalesTransactionGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getUoMAccess().getAlternatives(), "rule__UoM__Alternatives");
			builder.put(grammarAccess.getTransactionTypeAccess().getAlternatives(), "rule__TransactionType__Alternatives");
			builder.put(grammarAccess.getPaymentMethodAccess().getAlternatives(), "rule__PaymentMethod__Alternatives");
			builder.put(grammarAccess.getTaxTypeAccess().getAlternatives(), "rule__TaxType__Alternatives");
			builder.put(grammarAccess.getCompanyAccess().getGroup(), "rule__Company__Group__0");
			builder.put(grammarAccess.getCompanyAccess().getGroup_3(), "rule__Company__Group_3__0");
			builder.put(grammarAccess.getCompanyAccess().getGroup_8(), "rule__Company__Group_8__0");
			builder.put(grammarAccess.getCompanyAccess().getGroup_10(), "rule__Company__Group_10__0");
			builder.put(grammarAccess.getCompanyAccess().getGroup_10_3(), "rule__Company__Group_10_3__0");
			builder.put(grammarAccess.getAddressAccess().getGroup(), "rule__Address__Group__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_3(), "rule__Address__Group_3__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_4(), "rule__Address__Group_4__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_5(), "rule__Address__Group_5__0");
			builder.put(grammarAccess.getAddressAccess().getGroup_6(), "rule__Address__Group_6__0");
			builder.put(grammarAccess.getStoreAccess().getGroup(), "rule__Store__Group__0");
			builder.put(grammarAccess.getStoreAccess().getGroup_4(), "rule__Store__Group_4__0");
			builder.put(grammarAccess.getStoreAccess().getGroup_4_3(), "rule__Store__Group_4_3__0");
			builder.put(grammarAccess.getTransactionAccess().getGroup(), "rule__Transaction__Group__0");
			builder.put(grammarAccess.getTransactionAccess().getGroup_2(), "rule__Transaction__Group_2__0");
			builder.put(grammarAccess.getTransactionAccess().getGroup_3(), "rule__Transaction__Group_3__0");
			builder.put(grammarAccess.getTransactionAccess().getGroup_13(), "rule__Transaction__Group_13__0");
			builder.put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
			builder.put(grammarAccess.getItemAccess().getGroup_3(), "rule__Item__Group_3__0");
			builder.put(grammarAccess.getItemAccess().getGroup_4(), "rule__Item__Group_4__0");
			builder.put(grammarAccess.getItemAccess().getGroup_5(), "rule__Item__Group_5__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getPriceAccess().getGroup(), "rule__Price__Group__0");
			builder.put(grammarAccess.getCustomerAccess().getGroup(), "rule__Customer__Group__0");
			builder.put(grammarAccess.getCustomerAccess().getGroup_4(), "rule__Customer__Group_4__0");
			builder.put(grammarAccess.getCustomerAccess().getGroup_5(), "rule__Customer__Group_5__0");
			builder.put(grammarAccess.getCustomerAccess().getGroup_6(), "rule__Customer__Group_6__0");
			builder.put(grammarAccess.getCashierAccess().getGroup(), "rule__Cashier__Group__0");
			builder.put(grammarAccess.getCashierAccess().getGroup_4(), "rule__Cashier__Group_4__0");
			builder.put(grammarAccess.getCashierAccess().getGroup_5(), "rule__Cashier__Group_5__0");
			builder.put(grammarAccess.getLineItemAccess().getGroup(), "rule__LineItem__Group__0");
			builder.put(grammarAccess.getLineItemAccess().getGroup_2(), "rule__LineItem__Group_2__0");
			builder.put(grammarAccess.getLineItemAccess().getGroup_7(), "rule__LineItem__Group_7__0");
			builder.put(grammarAccess.getLineItemAccess().getGroup_8(), "rule__LineItem__Group_8__0");
			builder.put(grammarAccess.getLineItemAccess().getGroup_9(), "rule__LineItem__Group_9__0");
			builder.put(grammarAccess.getCardAccess().getGroup(), "rule__Card__Group__0");
			builder.put(grammarAccess.getCardAccess().getGroup_2(), "rule__Card__Group_2__0");
			builder.put(grammarAccess.getCardAccess().getGroup_3(), "rule__Card__Group_3__0");
			builder.put(grammarAccess.getTaxAccess().getGroup(), "rule__Tax__Group__0");
			builder.put(grammarAccess.getDiscountAccess().getGroup(), "rule__Discount__Group__0");
			builder.put(grammarAccess.getAdditionalChargeAccess().getGroup(), "rule__AdditionalCharge__Group__0");
			builder.put(grammarAccess.getCompanyAccess().getNameAssignment_1(), "rule__Company__NameAssignment_1");
			builder.put(grammarAccess.getCompanyAccess().getCodiceAssignment_3_1(), "rule__Company__CodiceAssignment_3_1");
			builder.put(grammarAccess.getCompanyAccess().getAddressAssignment_4(), "rule__Company__AddressAssignment_4");
			builder.put(grammarAccess.getCompanyAccess().getStoreAssignment_7(), "rule__Company__StoreAssignment_7");
			builder.put(grammarAccess.getCompanyAccess().getStoreAssignment_8_1(), "rule__Company__StoreAssignment_8_1");
			builder.put(grammarAccess.getCompanyAccess().getTransactionAssignment_10_2(), "rule__Company__TransactionAssignment_10_2");
			builder.put(grammarAccess.getCompanyAccess().getTransactionAssignment_10_3_1(), "rule__Company__TransactionAssignment_10_3_1");
			builder.put(grammarAccess.getAddressAccess().getStreetAssignment_3_1(), "rule__Address__StreetAssignment_3_1");
			builder.put(grammarAccess.getAddressAccess().getCityAssignment_4_1(), "rule__Address__CityAssignment_4_1");
			builder.put(grammarAccess.getAddressAccess().getCountryAssignment_5_1(), "rule__Address__CountryAssignment_5_1");
			builder.put(grammarAccess.getAddressAccess().getTelephoneAssignment_6_1(), "rule__Address__TelephoneAssignment_6_1");
			builder.put(grammarAccess.getStoreAccess().getNameAssignment_2(), "rule__Store__NameAssignment_2");
			builder.put(grammarAccess.getStoreAccess().getItemAssignment_4_2(), "rule__Store__ItemAssignment_4_2");
			builder.put(grammarAccess.getStoreAccess().getItemAssignment_4_3_1(), "rule__Store__ItemAssignment_4_3_1");
			builder.put(grammarAccess.getTransactionAccess().getTransactionNumberAssignment_2_1(), "rule__Transaction__TransactionNumberAssignment_2_1");
			builder.put(grammarAccess.getTransactionAccess().getIssuedDateAssignment_3_1(), "rule__Transaction__IssuedDateAssignment_3_1");
			builder.put(grammarAccess.getTransactionAccess().getTransactionTypeAssignment_5(), "rule__Transaction__TransactionTypeAssignment_5");
			builder.put(grammarAccess.getTransactionAccess().getPaymentMethodAssignment_7(), "rule__Transaction__PaymentMethodAssignment_7");
			builder.put(grammarAccess.getTransactionAccess().getCustomerAssignment_8(), "rule__Transaction__CustomerAssignment_8");
			builder.put(grammarAccess.getTransactionAccess().getCashierAssignment_9(), "rule__Transaction__CashierAssignment_9");
			builder.put(grammarAccess.getTransactionAccess().getLineItemAssignment_12(), "rule__Transaction__LineItemAssignment_12");
			builder.put(grammarAccess.getTransactionAccess().getLineItemAssignment_13_1(), "rule__Transaction__LineItemAssignment_13_1");
			builder.put(grammarAccess.getTransactionAccess().getCardAssignment_15(), "rule__Transaction__CardAssignment_15");
			builder.put(grammarAccess.getItemAccess().getNameAssignment_1(), "rule__Item__NameAssignment_1");
			builder.put(grammarAccess.getItemAccess().getCodeAssignment_3_1(), "rule__Item__CodeAssignment_3_1");
			builder.put(grammarAccess.getItemAccess().getBatchAssignment_4_1(), "rule__Item__BatchAssignment_4_1");
			builder.put(grammarAccess.getItemAccess().getDescriptionAssignment_5_1(), "rule__Item__DescriptionAssignment_5_1");
			builder.put(grammarAccess.getItemAccess().getUomAssignment_7(), "rule__Item__UomAssignment_7");
			builder.put(grammarAccess.getItemAccess().getAvailableNumberAssignment_9(), "rule__Item__AvailableNumberAssignment_9");
			builder.put(grammarAccess.getItemAccess().getIsActiveAssignment_11(), "rule__Item__IsActiveAssignment_11");
			builder.put(grammarAccess.getItemAccess().getUnitPriceAssignment_13(), "rule__Item__UnitPriceAssignment_13");
			builder.put(grammarAccess.getPriceAccess().getSellingPriceAssignment_3(), "rule__Price__SellingPriceAssignment_3");
			builder.put(grammarAccess.getCustomerAccess().getNameAssignment_2(), "rule__Customer__NameAssignment_2");
			builder.put(grammarAccess.getCustomerAccess().getSurNameAssignment_4_1(), "rule__Customer__SurNameAssignment_4_1");
			builder.put(grammarAccess.getCustomerAccess().getIdentityNumberAssignment_5_1(), "rule__Customer__IdentityNumberAssignment_5_1");
			builder.put(grammarAccess.getCustomerAccess().getPhoneNumberAssignment_6_1(), "rule__Customer__PhoneNumberAssignment_6_1");
			builder.put(grammarAccess.getCustomerAccess().getCardAssignment_7(), "rule__Customer__CardAssignment_7");
			builder.put(grammarAccess.getCustomerAccess().getCustomerAssignment_8(), "rule__Customer__CustomerAssignment_8");
			builder.put(grammarAccess.getCustomerAccess().getCashierAssignment_9(), "rule__Customer__CashierAssignment_9");
			builder.put(grammarAccess.getCashierAccess().getNameAssignment_2(), "rule__Cashier__NameAssignment_2");
			builder.put(grammarAccess.getCashierAccess().getSurNameAssignment_4_1(), "rule__Cashier__SurNameAssignment_4_1");
			builder.put(grammarAccess.getCashierAccess().getEmployeeIdAssignment_5_1(), "rule__Cashier__EmployeeIdAssignment_5_1");
			builder.put(grammarAccess.getCashierAccess().getCustomerAssignment_6(), "rule__Cashier__CustomerAssignment_6");
			builder.put(grammarAccess.getCashierAccess().getCashierAssignment_7(), "rule__Cashier__CashierAssignment_7");
			builder.put(grammarAccess.getLineItemAccess().getCodeAssignment_2_1(), "rule__LineItem__CodeAssignment_2_1");
			builder.put(grammarAccess.getLineItemAccess().getQuantityAssignment_4(), "rule__LineItem__QuantityAssignment_4");
			builder.put(grammarAccess.getLineItemAccess().getItemAssignment_6(), "rule__LineItem__ItemAssignment_6");
			builder.put(grammarAccess.getLineItemAccess().getTaxAssignment_7_1(), "rule__LineItem__TaxAssignment_7_1");
			builder.put(grammarAccess.getLineItemAccess().getDiscountAssignment_8_1(), "rule__LineItem__DiscountAssignment_8_1");
			builder.put(grammarAccess.getLineItemAccess().getAdditionalChargeAssignment_9_1(), "rule__LineItem__AdditionalChargeAssignment_9_1");
			builder.put(grammarAccess.getCardAccess().getCardNumberAssignment_2_1(), "rule__Card__CardNumberAssignment_2_1");
			builder.put(grammarAccess.getCardAccess().getExpiryDateAssignment_3_1(), "rule__Card__ExpiryDateAssignment_3_1");
			builder.put(grammarAccess.getCardAccess().getCardHolderAssignment_5(), "rule__Card__CardHolderAssignment_5");
			builder.put(grammarAccess.getTaxAccess().getTaxTypeAssignment_3(), "rule__Tax__TaxTypeAssignment_3");
			builder.put(grammarAccess.getTaxAccess().getTaxableAmountAssignment_5(), "rule__Tax__TaxableAmountAssignment_5");
			builder.put(grammarAccess.getTaxAccess().getTaxAmountAssignment_7(), "rule__Tax__TaxAmountAssignment_7");
			builder.put(grammarAccess.getDiscountAccess().getPercentageAssignment_3(), "rule__Discount__PercentageAssignment_3");
			builder.put(grammarAccess.getDiscountAccess().getAmountAssignment_5(), "rule__Discount__AmountAssignment_5");
			builder.put(grammarAccess.getAdditionalChargeAccess().getServiceChargeAssignment_3(), "rule__AdditionalCharge__ServiceChargeAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SalesTransactionGrammarAccess grammarAccess;

	@Override
	protected InternalSalesTransactionParser createParser() {
		InternalSalesTransactionParser result = new InternalSalesTransactionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SalesTransactionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SalesTransactionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
