/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SalesTransactionUiModule extends AbstractSalesTransactionUiModule {

	public SalesTransactionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
