/*
 * generated by Xtext 2.25.0
 */
package xtext.sales.assignment3.transaction.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import xtext.assignment3.salestransaction.ui.internal.SalestransactionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SalesTransactionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SalestransactionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SalestransactionActivator activator = SalestransactionActivator.getInstance();
		return activator != null ? activator.getInjector(SalestransactionActivator.XTEXT_SALES_ASSIGNMENT3_TRANSACTION_SALESTRANSACTION) : null;
	}

}
